### PR TITLE
Upgrades setup for Py3 conversion and runs 2to3

### PR DESCRIPTION
**Pull request by powellc**
The start of moving Gittle over to Python 3+

A few caveats here: I just updated setup.py requirements and ran 2to3 over the project. This means that it will break 2.7 compat. Using this pull request diff as a guide, one ought to step through the files and to the laborious work of try/except blocks for 2/3 differences.

I'll try to get to it soon, but no promises.

### CODE REVIEW

**Comment by forresthopkinsa** [comment]
Forgive the silly question, but are there any use cases where a user would need both Py2.7 *and* Py3+ compat in one library?

I mean, they would never have two Python installations referencing the same installation directory anyways, right? I don't know if I'm making sense.

My point is, maybe it wouldn't be worth the effort to keep Gittle and Gittle3 packaged together? Please correct me if I'm missing something important.

P.S. Have you tested this yet? I'll probably be able to do some testing on your branch this weekend if it isn't merged by then.

**Comment by powellc** [comment]
@forresthopkinsa that's a fair point. I think most libraries tend to mix compatibility, but in the case of a project not being supported for so long such as Gittle, perhaps a fork for 3 compat isn't a terrible idea.

I could rename my fork gittle3 and proceed thusly.

Also, I did some preliminary testing, and the examples/clone.py file breaks with an issue from the Dulwich upgrade, so I need to take a look at that, but may not be able to until tomorrow or Thursday.

Thanks for your willingness to help :)

**Comment by AaronO** [comment]
@powellc @forresthopkinsa Happy to get this merged.

I think it would be nice if the one library worked on python2 and python3, I think that's the norm, unfortunately python2 is still the default on many systems (OS X etc ...). So by not supporting python2 out of the box we would force a lot of developers to have to consider shipping python3 along with their code.

Supporting both should be relatively minimal work. I'll merge this now, and maybe we can then get it working on python2 again.

I still work a lot with git these days (working on [GitBook](https://www.gitbook.com)), but not so much with Python these days. (Still a great language and I often use `ipython` as my calculator and for quick/small tools).

**Comment by powellc** [comment]
@AaronO thanks for the prompt merge, and the useful thoughts. I think you're right about not forking the app. I'll try to find sometime tomorrow to go through add some try/except blocks for Python 2 and open a new pull request.

**Comment by forresthopkinsa** [comment]
Sounds good, I'll check back this weekend and lend a hand where I can. I'm
glad this project is alive again 👍

**Pull request merged**
