### PR TITLE
fixed some error in Python3

### PR DESCRIPTION
**Pull request by gsw945**
2 modules _`urlparse`_ and _`StringIO`_ import changed in Python 3.

`040000` in Python 2, changed to `0o40000` in Python 3

_`basestring`_ is not defined in Python 3, replaced with _`str`_

### CODE REVIEW

**Comment by hanbeibei** [comment]
does these change work? why there are some import error that need to be fixed, 

I had tried but not fixed, please refer to this: http://stackoverflow.com/questions/12172791/changes-in-import-statement-python3

maybe I still need more time to figure out the  python 3 module import mechanism

**Comment by hanbeibei** [comment]
the problem which I met:
File "C:\Python33\lib\site-packages\gittle-0.2.1-py3.3.egg\gittle\utils__init__.py", line 1, in <
module>
from . import paths, urls, git

there are some describe on issue 12, but I was in mac, and install with pip, there no error during installation process, it should not be happened

**Comment by hanbeibei** [comment]
maybe we need this __future__:
https://docs.python.org/3/library/__future__.html?highlight=__future__#module-__future__

**Comment by AaronO** [comment]
@gsw945 Thanks :+1:

**Pull request merged**
